export const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const icons = {
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
 week:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18m-13 4h1m6 0h1"/>',
 tasks:'<rect x="5" y="3" width="15" height="18" rx="3"/><path d="m8 9 1 1 2-2m3 1h3m-9 6 1 1 2-2m3 1h3"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',
 arrow:'<path d="M19 12H5m6-6-6 6 6 6"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 spark:'<path d="m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6L12 3Z"/>',
 undo:'<path d="M4 10h9a6 6 0 1 1 0 12M4 10l5-5m-5 5 5 5"/>',
 trash:'<path d="M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 mic:'<rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5.5 11a6.5 6.5 0 0 0 13 0M12 17.5V21m-3.5 0h7"/>',
 help:'<circle cx="12" cy="12" r="9"/><path d="M9.6 9.3a2.5 2.5 0 1 1 3.4 2.6c-.6.3-1 .8-1 1.5v.4M12 16.8v.2"/>'
};
export const icon = (name, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.sun}</svg>`;
export const duration = minutes => { const hours=Math.floor(minutes/60),rest=minutes%60; const whole=hours===1?'שעה':hours===2?'שעתיים':hours+' שעות'; return hours?whole+(rest?' ו־'+rest+' דקות':''):minutes+' דקות'; };
const dateLabel = date => new Date(date+'T12:00:00').toLocaleDateString('he-IL',{day:'numeric',month:'long'});
const fullDate = date => new Date(date+'T12:00:00').toLocaleDateString('he-IL',{day:'numeric',month:'long',year:'numeric'});
const dayLabel = date => new Date(date+'T12:00:00').toLocaleDateString('he-IL',{weekday:'long'});
const catLabel = cat => ({study:'לימודים',personal:'אישי',work:'עבודה'}[cat] || 'לימודים');
export function shell() {
 return `<aside class="sidebar"><a href="#" class="brand" aria-label="StudyFlow, היום"><img class="brand-mark" src="src/studyflow/brand/mark.svg" alt="" width="36" height="36"><span>StudyFlow<small class="brand-tagline">כל המשימות, במקום אחד.</small></span></a><button class="primary sidebar-add" data-action="add">${icon('plus')} הוספת משימה</button><button class="helper-button" data-action="helper">${icon('mic')} <span>העוזר החכם<small>אומרים, והוא מוסיף</small></span></button><nav class="desktop-nav" aria-label="ניווט ראשי">${navigation()}</nav><button class="sidebar-settings sidebar-help" data-action="tour">${icon('help')}<span>איך משתמשים?</span></button><button class="sidebar-settings" data-action="settings">${icon('settings')}<span>העדפות</span></button></aside><div class="workspace"><header class="topbar"><a href="#" class="mobile-brand brand"><img class="brand-mark" src="src/studyflow/brand/mark.svg" alt="" width="32" height="32"><b>StudyFlow</b></a><div class="topbar-actions"><button class="icon-button" data-action="helper" aria-label="העוזר החכם: להגיד מה צריך לעשות">${icon('mic')}</button><button class="icon-button" data-action="tour" aria-label="איך משתמשים? הדרכה קצרה">${icon('help')}</button><button class="icon-button" data-action="settings" aria-label="העדפות תכנון">${icon('settings')}</button></div></header><main id="main" tabindex="-1"></main></div><nav class="bottom-nav" aria-label="ניווט בנייד">${navigation()}<button class="mobile-add" data-action="add" aria-label="הוספת משימה או התחייבות">${icon('plus')}</button></nav><dialog id="sheet" aria-labelledby="dialog-title"></dialog><div id="toast" class="toast" role="status" aria-live="polite"></div>`;
}
function navigation(){return [['today','sun','היום'],['week','week','השבוע'],['tasks','tasks','משימות']].map(([view,img,label])=>`<button data-view="${view}">${icon(img)}<span>${label}</span></button>`).join('');}
export function renderMain({state,plan,view,selected,dates,today}){
 const empty = !state.tasks.length && !(state.eventSeries||state.events).length;
 const completed=state.tasks.filter(t=>t.done).length;
 const title = view==='tasks' ? 'המשימות שלי' : view==='week' ? 'השבוע שלי' : 'היום';
 const progress=state.tasks.length&&view!=='week'?`<div class="progress-row"><span>הושלמו <b>${completed}</b> מתוך ${state.tasks.length} משימות</span><div class="progress-track"><i style="width:${Math.round(completed/state.tasks.length*100)}%"></i></div></div>`:'';
 const overflow=plan.unscheduled.length?`<details class="overflow-card"><summary>${plan.unscheduled.length===1?'משימה אחת לא נכנסה':plan.unscheduled.length+' משימות לא נכנסו'} לזמן הפנוי</summary>${plan.unscheduled.map(t=>`<div class="overflow-item"><div><b>${escapeHTML(t.title)}</b> <small>· עוד ${duration(t.minutes)}</small><p>${escapeHTML(t.reason)}</p></div><button class="text-button" data-action="edit-task" data-id="${escapeHTML(t.taskId)}">עדכון</button></div>`).join('')}<button class="text-button" data-action="settings">להרחיב את השעות הפנויות ${icon('arrow')}</button></details>`:'';
 return `${state.demo?'<div class="demo-banner">זו תוכנית לדוגמה.<button data-action="exit-demo">חזרה לתוכנית שלי '+icon('arrow')+'</button></div>':''}<section class="page-heading"><div class="eyebrow">${dayLabel(today)} · ${dateLabel(today)}</div><h1>${title}</h1></section>${empty && view==='today'?emptyWelcome():`${progress}${overflow}<section class="primary-content">${view==='today'?weekStrip(dates,selected,today,plan,state):''}${view==='tasks'?taskList(state)+eventList(state.eventSeries||state.events):view==='week'?weekView(dates,plan,state,today):dayView(selected,plan,state,today,empty)}</section>`}`;
}
function emptyWelcome(){return `<section class="welcome"><div class="welcome-icon">${icon('tasks')}</div><h2>עוד אין כאן כלום</h2><p>מוסיפים משימה, וקובעים לה זמן בשבוע באופן אוטומטי.</p><button class="primary" data-action="add">${icon('plus')} הוספת משימה ראשונה</button><button class="demo-button helper-welcome" data-action="helper">${icon('mic')} או פשוט להגיד בקול</button><button class="demo-button" data-action="demo">לראות דוגמה</button></section>`;}
function weekStrip(dates,selected,today,plan,state){return `<div class="week-strip" aria-label="בחירת יום">${dates.map(date=>`<button class="day-chip ${date===selected?'selected':''}" data-date="${date}" aria-pressed="${date===selected}"><span>${date===today?'היום':dayLabel(date).replace('יום ','')}</span><b>${new Date(date+'T12:00:00').getDate()}</b><i class="${plan.sessions.some(s=>s.date===date)||state.events.some(e=>e.date===date)?'has-items':''}"></i></button>`).join('')}</div>`;}
function dayView(date,plan,state,today,empty){
 const items=[...plan.sessions.filter(s=>s.date===date),...state.events.filter(e=>e.date===date).map(e=>({...e,fixed:true}))].sort((a,b)=>a.start.localeCompare(b.start));
 const minutes=items.filter(i=>!i.fixed).reduce((sum,i)=>sum+i.minutes,0);
 return `<div class="section-heading"><div><h2>${date===today?'מה מתוכנן להיום':dayLabel(date)+', '+dateLabel(date)}</h2><p>${items.length?`${duration(minutes)} של משימות`:'אין כאן כלום עדיין'}</p></div></div>${items.length?`<div class="timeline">${items.map(sessionCard).join('')}</div>`:`<div class="day-empty">${icon('sun')}<h3>היום הזה פנוי</h3><p>${empty?'מוסיפים משימה, והזמן שלה יופיע כאן.':'אין משימות שתוכננו ליום הזה.'}</p><button class="text-button" data-action="add">${icon('plus')} להוסיף משהו ליום</button></div>`}`;
}
function sessionCard(s){return `<article class="timeline-row"><div class="time"><b>${s.start}</b><span>${s.end}</span></div><div class="timeline-point ${s.fixed?'fixed':''}"></div><div class="session-card ${s.fixed?'fixed-card':escapeHTML(s.category)}"><div class="session-head"><span class="category">${s.fixed?'פעילות בשעה קבועה':catLabel(s.category)}</span>${!s.fixed?`<span class="session-duration">${duration(s.minutes)}</span>`:''}</div><h3>${escapeHTML(s.title)}</h3>${s.fixed&&s.repeat==='weekly'?`<p class="series-end">חוזרת בכל שבוע${s.repeatUntil?' · מסתיימת ב־'+fullDate(s.repeatUntil):' · ללא תאריך סיום'}</p>`:''}${s.preferenceFallback?`<p class="preference-note">${escapeHTML(s.preferenceFallbackReason)}</p>`:""}${s.fixed?`<button class="text-button" data-action="edit-event" data-id="${escapeHTML(s.id)}">עריכה</button> <button class="text-button muted" data-action="delete-event" data-id="${escapeHTML(s.id)}" data-date="${s.date}">${s.repeat==='weekly'?'ביטול מועד':'ביטול התחייבות'}</button>`:`<div class="session-actions"><button class="complete-button" data-action="complete-session" data-id="${escapeHTML(s.id)}">${icon('check')} סיימתי</button><button class="text-button muted" data-action="delay" data-id="${escapeHTML(s.id)}">לדחות בשעה</button></div>`}</div></article>`;}
function weekView(dates,plan,state,today){return `<div class="section-heading"><div><h2>כל הימים</h2><p>${duration(plan.plannedMinutes)} של משימות השבוע</p></div></div><div class="week-agenda">${dates.map(date=>{const sessions=plan.sessions.filter(s=>s.date===date);const events=state.events.filter(e=>e.date===date);return `<article class="agenda-day"><button class="agenda-date" data-date="${date}"><b>${date===today?'היום':dayLabel(date)}</b><span>${dateLabel(date)}</span></button><div>${[...sessions,...events.map(e=>({...e,fixed:true}))].sort((a,b)=>a.start.localeCompare(b.start)).map(s=>`<div class="agenda-item ${s.fixed?'fixed':''}"><span>${s.start}</span><b>${escapeHTML(s.title)}</b><small>${s.fixed?'קבוע':duration(s.minutes)}</small></div>`).join('')||'<p class="free-space">יום פנוי</p>'}</div></article>`;}).join('')}</div>`;}
function taskList(state){return `<div class="task-list">${state.tasks.length?state.tasks.map(t=>`<article class="task-item ${t.done?'is-done':''}"><button class="task-check ${t.done?'checked':''}" data-action="toggle-task" data-id="${escapeHTML(t.id)}" aria-label="${t.done?'לפתוח מחדש':'לסמן כהושלמה'}: ${escapeHTML(t.title)}">${t.done?icon('check'):''}</button><div><h3>${escapeHTML(t.title)}</h3><p>${catLabel(t.category)} · ${duration(Math.max(0,t.minutes-(t.completedMinutes||0)))} נותרו · עד ${dateLabel(t.deadline)}</p></div><button class="text-button edit-task" data-action="edit-task" data-id="${escapeHTML(t.id)}" aria-label="עריכת ${escapeHTML(t.title)}">עריכה</button><button class="icon-button muted" data-action="delete-task" data-id="${escapeHTML(t.id)}" aria-label="מחיקת ${escapeHTML(t.title)}">${icon('trash')}</button></article>`).join(''):`<div class="day-empty">${icon('tasks')}<h3>אין משימות עדיין</h3><p>כל מה שצריך לעשות, במקום אחד.</p><button class="primary" data-action="add">${icon('plus')} משימה חדשה</button></div>`}</div>`;}

function eventList(events){
 if(!events.length)return '';
 const days=['א׳','ב׳','ג׳','ד׳','ה׳','ו׳','שבת'];
 return '<section class="commitments"><div class="section-heading"><div><h2>שעות קבועות</h2><p>שיעורים, עבודה ואימונים. לא נשבץ בהם משימות.</p></div></div>'+events.map(e=>`<article class="task-item"><span class="event-symbol">${icon('week')}</span><div><h3>${escapeHTML(e.title)}</h3><p>${e.repeat==='weekly'?'בכל שבוע · '+(e.weekdays?.length?e.weekdays:[new Date(e.date+'T12:00:00').getDay()]).map(d=>days[d]).join(', ')+' · מ־'+fullDate(e.date)+(e.repeatUntil?' · מסתיימת ב־'+fullDate(e.repeatUntil):' · ללא תאריך סיום'):dateLabel(e.date)}<br><bdi>${e.start}–${e.end}</bdi></p></div><button class="text-button" data-action="edit-event" data-id="${escapeHTML(e.id)}" aria-label="עריכת ${escapeHTML(e.title)}">עריכה</button><button class="icon-button muted" data-action="delete-event" data-id="${escapeHTML(e.id)}" aria-label="ביטול ${escapeHTML(e.title)}">${icon('trash')}</button></article>`).join('')+'</section>';
}
