import {escapeHTML as esc,icon,duration} from './views.mjs';
import {setupWeeklyWizard} from './weekly-wizard.mjs';
import {localDate} from './planner.mjs';
import {buildWeeklyPlan,previewNextWeek,acceptNextWeek,completeWeeklySession,moveWeeklySession,setSessionLocked,addDays,reviewAvailability} from './weekly.mjs';
const clone=x=>JSON.parse(JSON.stringify(x));
const loads=[['light','קל · יותר מקום לנשום'],['balanced','מאוזן'],['heavy','מלא · קצת יותר התקדמות']];
const energies=[['low','נמוכה · מפגשים קצרים'],['normal','רגילה'],['high','גבוהה']];
const options=(values,value)=>values.map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${t}</option>`).join('');
const heading=t=>`<div class="sheet-top"><h2 id="dialog-title">${t}</h2><button class="icon-button" data-action="close" aria-label="סגירה">${icon('close')}</button></div>`;
const error='<p id="weekly-error" class="form-error" role="alert"></p>';
const submit=t=>`${error}<button class="primary submit-button" type="submit">${t}</button>`;
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('he-IL',{day:'numeric',month:'long'});
const pace=w=>`<label for="weekly-load">איזה עומס מתאים לך?</label><select id="weekly-load" name="load">${options(loads,w.load)}</select><label for="weekly-energy">איך האנרגיה שלך כרגע?</label><select id="weekly-energy" name="energy">${options(energies,w.energy)}</select><small class="field-help">זו בחירה שלך, לא ניחוש שלנו. תמיד משאירים הפסקות ומכבדים שעות קבועות.</small>`;
export function weeklyPanel(state,plan,view){
 const availability=reviewAvailability(state);const w=state.weekly,goals=state.goals.filter(g=>g.repeatWeekly||g.weekStart===w.weekStart);
 const list=view==='tasks'?`<section class="weekly-goals"><h2>המטרות שלי השבוע</h2>${goals.map(g=>{const done=w.completions.filter(c=>c.goalId===g.id).reduce((a,c)=>a+c.minutes,0);return `<article class="task-item"><div><h3>${esc(g.title)}</h3><p>${duration(done)} מתוך ${duration(g.minutes)}${g.repeatWeekly?' · מתחדשת בכל שבוע':''}</p></div><button class="text-button" data-weekly="goal" data-id="${esc(g.id)}">עריכה</button></article>`;}).join('')||'<p class="field-help">לימודים, אימון או רעיון משלך. בוחרים יעד זמן ואנחנו מוצאים לו מקום.</p>'}<button class="text-button" data-weekly="course">${icon('plus')} הוספת מקצוע</button>${state.courses.map(c=>`<button class="text-button" data-weekly="course" data-id="${esc(c.id)}">${esc(c.name)} · עריכה</button>`).join('')}</section>`:'';
 return `<section class="weekly-intro"><div><span class="eyebrow">תכנון אישי · חינם · ללא AI</span><p>השבוע שלך · ${dateLabel(w.weekStart)}–${dateLabel(addDays(w.weekStart,6))}</p>${plan.needsReview?'<p role="status">השבוע הסתיים. אפשר לסכם ולהכין את הבא, בלי לאבד את המטרות.</p>':''}</div><div class="weekly-actions"><button class="primary" data-weekly="goal">${icon('plus')} מטרה לשבוע</button><button class="text-button" data-weekly="pace">לתכנן את השבוע</button><button class="text-button" data-weekly="change">היום השתנה לי</button>${w.nextWeek?'<button class="text-button" data-weekly="edit-next">עריכת השבוע הבא</button>':`<button class="text-button" data-weekly="review" ${availability.open?'':'disabled'}>${availability.submitted?'הסיכום נשמר':availability.open?'סיכום ושבוע הבא':'הסיכום נפתח במוצ״ש ב־20:00'}</button>`}</div></section>${w.nextWeek?`<p role="status">התוכנית לשבוע שמתחיל ב־${dateLabel(w.nextWeek.weekly.weekStart)} אושרה. היא תיפתח כאן בתחילת השבוע.</p>`:''}${plan.blockedSessions.map(s=>`<p class="weekly-gap" role="status">המפגש הנעול ״${esc(s.title)}״ מתנגש בזמינות החדשה. <button class="text-button" data-weekly="move" data-id="${esc(s.id)}">לבחור זמן אחר</button><button class="text-button" data-weekly="lock" data-id="${esc(s.id)}">לשחרר ולתכנן מחדש</button></p>`).join('')}${list}`;
}
export function setupWeeklyUI(ctx){
 let proposal=null,nextWeek=false;const wizard=setupWeeklyWizard(ctx);
 const {getState,getPlan,open,close,mutate,replace,toast}=ctx;
 const commit=(value,message)=>{mutate(()=>replace(value),message);close();};
 const preview=(value,next=false)=>wizard.preview(value,next);
 function showGoal(id,courseId='',topicId=''){
  const state=getState(),g=state.goals.find(g=>g.id===id)||{minutes:120,category:'study',priority:'normal',sessionMinutes:50,preferredTime:'any',courseId,topicId,title:state.courses.find(c=>c.id===courseId)?.topics?.find(t=>t.id===topicId)?.title||''};
  open(`${heading(id?'עדכון המטרה':'מה חשוב לך לקדם השבוע?')}<form id="weekly-goal" data-id="${esc(id||'')}" data-topic-id="${esc(g.topicId||'')}"><label for="goal-title">המטרה שלי</label><input id="goal-title" name="title" value="${esc(g.title||'')}" maxlength="120" required autofocus placeholder="לתרגל נושא קשה, להתאמן, לעבוד על רעיון"><label for="goal-hours">כמה שעות להקדיש השבוע?</label><input id="goal-hours" name="hours" type="number" min="0.25" max="168" step="0.25" value="${g.minutes/60}" required><label class="repeat-option"><input name="repeatWeekly" type="checkbox" ${g.repeatWeekly?'checked':''}> אותה מטרה גם בשבועות הבאים</label><details class="advanced"><summary>מקצוע, חשיבות ושעות נוחות</summary><label for="goal-course">מקצוע (לא חובה)</label><select id="goal-course" name="courseId"><option value="">ללא מקצוע</option>${state.courses.map(c=>`<option value="${esc(c.id)}" ${g.courseId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select><label for="goal-category">סוג מטרה</label><select id="goal-category" name="category">${options([['study','לימודים'],['personal','אישי ואימונים'],['work','עבודה ויזמות']],g.category)}</select><label for="goal-priority">חשיבות</label><select id="goal-priority" name="priority">${options([['normal','רגילה'],['high','גבוהה'],['low','כשיש זמן']],g.priority)}</select><label for="goal-time">שעות נוחות</label><select id="goal-time" name="preferredTime">${options([['any','לפי ההעדפות שלי'],['morning','בוקר'],['afternoon','צהריים'],['evening','ערב']],g.preferredTime)}</select><label for="goal-session">משך מפגש נוח (דקות)</label><input id="goal-session" name="sessionMinutes" type="number" min="15" max="180" step="5" value="${g.sessionMinutes}"></details>${submit('לראות איך זה משתלב')}</form>${id?`<button class="text-button muted" data-weekly="remove-goal" data-id="${esc(id)}">להסיר את המטרה השבועית</button>`:''}`);
 }
 document.addEventListener('click',event=>{
  const t=event.target.closest('[data-weekly]');if(!t)return;
  const state=getState(),id=t.dataset.id;
  try{switch(t.dataset.weekly){
   case 'goal':showGoal(id);break;
   case 'approve':if(proposal)commit(nextWeek?acceptNextWeek(state,proposal):proposal,'התוכנית אושרה. אפשר לשנות אותה בכל רגע.');proposal=null;break;
   case 'pace':wizard.start();break;
   case 'edit-next':if(state.weekly.nextWeek)wizard.start({...state,...state.weekly.nextWeek},true);break;
   case 'legacy-pace':open(`${heading('תוכנית שמתאימה לחיים שלך')}<form id="weekly-pace">${pace(state.weekly)}${submit('להכין הצעה')}</form><button class="text-button" data-action="settings">שעות נוחות, ימים והפסקות</button>`);break;
   case 'change':open(`${heading('מה מתאים לך היום?')}<form id="weekly-change"><label for="changed-date">באיזה יום?</label><input id="changed-date" name="date" type="date" min="${state.weekly.weekStart}" max="${addDays(state.weekly.weekStart,6)}" value="${localDate()}" required><label for="changed-minutes">כמה דקות אפשר להקדיש למטרות?</label><input id="changed-minutes" name="maxMinutes" type="number" min="0" max="720" step="5" value="30" required><small class="field-help">0 = היום לא מסתדר. ההתחייבויות הקבועות נשארות.</small><label for="changed-energy">האנרגיה שלי</label><select id="changed-energy" name="energy">${options(energies,'normal')}</select>${submit('לראות התאמה לשבוע')}</form>`);break;
   case 'review':if(!reviewAvailability(state).open){toast('סיכום השבוע נפתח במוצ״ש ב־20:00, ואפשר להשלים אותו גם באיחור.');break;}open(`${heading('נסגור שבוע ונפנה מקום לבא')}<p>דיווחת על ${duration(state.weekly.completions.reduce((a,c)=>a+c.minutes,0))} של התקדמות. מה שלא עודכן אינו נחשב כישלון.</p><form id="weekly-review">${pace(state.weekly)}<fieldset class="weekly-carry"><legend>מטרות חד־פעמיות להמשך (לבחירתך)</legend>${state.goals.filter(g=>!g.repeatWeekly&&g.weekStart===state.weekly.weekStart).map(g=>`<label><input type="checkbox" name="carry" value="${esc(g.id)}">${esc(g.title)}</label>`).join('')||'<p>אין מטרות חד־פעמיות להעברה.</p>'}</fieldset><label for="review-note">משהו לזכור לשבוע הבא? (לא חובה)</label><input id="review-note" name="note" maxlength="500"><small class="field-help">ההערה נשמרת לסיכום. התאמת התוכנית נעשית לפי העומס והאנרגיה שבחרת.</small>${submit('להכין את השבוע הבא')}</form>`);break;
   case 'course':{const c=state.courses.find(c=>c.id===id)||{};open(`${heading('המקצועות שלי')}<form id="weekly-course" data-id="${esc(id||'')}"><label for="course-name">שם המקצוע</label><input id="course-name" name="name" maxlength="120" value="${esc(c.name||'')}" required><label for="course-difficulty">איך הולך כרגע?</label><select id="course-difficulty" name="difficulty">${options([['1','די נוח'],['2','צריך תרגול'],['3','מאתגר — עדיף מקטעים קצרים']],String(c.difficulty||2))}</select><label for="course-exam">מועד מבחן (לא חובה)</label><input id="course-exam" name="examDate" type="date" value="${esc(c.examDate||'')}">${submit('לשמור מקצוע')}</form>`);break;}
   case 'complete':{const s=getState().weekly.sessions.find(s=>s.id===id);if(s)commit(completeWeeklySession(state,id,s.minutes),'ההתקדמות נשמרה. כל צעד נחשב.');break;}
   case 'partial':{const s=getState().weekly.sessions.find(s=>s.id===id);if(s)open(`${heading('כמה הספקת?')}<form id="weekly-partial" data-id="${esc(id)}"><label for="done-minutes">דקות שבוצעו מתוך ${s.minutes}</label><input id="done-minutes" name="minutes" type="number" min="0" max="${s.minutes}" step="1" value="${Math.floor(s.minutes/2)}" required><small class="field-help">השאר יישאר במטרה ונחפש לו מקום. 0 פירושו שלא הסתדר.</small>${submit('לעדכן התקדמות')}</form>`);break;}
   case 'move':{const s=getState().weekly.sessions.find(s=>s.id===id);if(s)open(`${heading('המפגש בזמן שמתאים לך')}<form id="weekly-move" data-id="${esc(id)}"><label for="move-date">תאריך</label><input id="move-date" name="date" type="date" min="${state.weekly.weekStart}" max="${addDays(state.weekly.weekStart,6)}" value="${s.date}" required><label for="move-time">שעה</label><input id="move-time" name="start" type="time" value="${s.start}" required><p class="field-help">נבדוק שאין התנגשות. הבחירה שלך תינעל כדי לשמור עליה.</p>${submit('להעביר ולנעול')}</form>`);break;}
   case 'lock':{const s=getState().weekly.sessions.find(s=>s.id===id);if(s)commit(setSessionLocked(state,id,!s.locked),s.locked?'המפגש פתוח לתכנון מחדש.':'המפגש נעול בזמן שבחרת.');break;}
   case 'remove-goal':{const next=clone(state);next.goals=next.goals.filter(g=>g.id!==id);next.weekly.sessions=next.weekly.sessions.filter(s=>s.goalId!==id);preview(next);break;}
  }}catch(e){toast(e.message);}
 });
 document.addEventListener('submit',event=>{
  const f=event.target;if(!f.id.startsWith('weekly-'))return;event.preventDefault();const fd=new FormData(f),state=getState(),next=clone(state);
  try{switch(f.id){
   case 'weekly-goal':{const title=String(fd.get('title')||'').trim(),minutes=Number(fd.get('hours'))*60;if(!title||!Number.isFinite(minutes)||minutes<15||minutes>10080)throw Error('נבחר שם ויעד זמן תקינים.');const g={id:f.dataset.id||crypto.randomUUID(),title,minutes,category:fd.get('category'),courseId:fd.get('courseId'),topicId:f.dataset.topicId||'',priority:fd.get('priority'),preferredTime:fd.get('preferredTime'),sessionMinutes:Number(fd.get('sessionMinutes')),repeatWeekly:fd.has('repeatWeekly'),weekStart:state.weekly.weekStart};next.goals=next.goals.filter(x=>x.id!==g.id).concat(g);next.weekly.sessions=next.weekly.sessions.filter(s=>s.goalId!==g.id||s.locked||s.date<localDate()||(s.date===localDate()&&s.start<new Date().toTimeString().slice(0,5)));preview(next);break;}
   case 'weekly-pace':next.weekly.sessions=next.weekly.sessions.filter(s=>s.locked||s.date<localDate()||(s.date===localDate()&&s.start<new Date().toTimeString().slice(0,5)));next.weekly.load=fd.get('load');next.weekly.energy=fd.get('energy');preview(next);break;
   case 'weekly-change':next.weekly.overrides=next.weekly.overrides.filter(x=>x.date!==fd.get('date')).concat({date:fd.get('date'),maxMinutes:Number(fd.get('maxMinutes')),energy:fd.get('energy')});preview(next);break;
   case 'weekly-review':wizard.start(previewNextWeek(state,new Date(),{carryGoalIds:fd.getAll('carry'),load:fd.get('load'),energy:fd.get('energy'),note:fd.get('note')}),true);break;
   case 'weekly-course':{const name=String(fd.get('name')||'').trim();if(!name)throw Error('צריך שם למקצוע.');const c={...state.courses.find(c=>c.id===f.dataset.id),id:f.dataset.id||crypto.randomUUID(),name,difficulty:Number(fd.get('difficulty')),examDate:fd.get('examDate')};next.courses=next.courses.filter(x=>x.id!==c.id).concat(c);commit(next,'המקצוע נשמר. אפשר לשייך אליו מטרות.');break;}
   case 'weekly-partial':commit(completeWeeklySession(state,f.dataset.id,Number(fd.get('minutes'))),'ההתקדמות נשמרה והשאר נשאר בתוכנית.');break;
   case 'weekly-move':commit(moveWeeklySession(state,f.dataset.id,fd.get('date'),fd.get('start')),'המפגש הועבר וננעל.');break;
  }}catch(e){f.querySelector('#weekly-error').textContent=e.message;}
 });
 return {addGoal:(courseId,topicId)=>showGoal(null,courseId,topicId)};
}
